spring.application.name=placement-portal
server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/placement_db
spring.data.mongodb.auto-index-creation=true

# JWT Secret Key (should be exactly 64 characters for HS512)
app.jwtSecret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwtExpirationMs=86400000

# Mail Server Configuration (Dummy config to avoid crash, will log to console or mock if needed)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=engg.chandraprakash01@gmail.com
spring.mail.password=Engg@9060
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# File upload properties
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Turn off debug logs
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO
